//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Afiliado
    {
        public int Id_Afiliado { get; set; }
        public int Id_Socio { get; set; }
        public string Parentesco { get; set; }
        [Display(Name = "Nombre Afiliado")]

        public string Nombre_Afiliado { get; set; }
        [Display(Name = "Apellido Afiliado")]

        public string Apellidos_Afiliado { get; set; }
    
        public virtual Socio Socio { get; set; }
    }
}
