//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Membresia
    {
        public int Id_Socio { get; set; }
        public int Id_Membresia { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_salida { get; set; }
    
        public virtual Membresia Membresia { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
