//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int id_usuario { get; set; }
        [Display (Name = "Nombre Usuario")]
        public string nombre_usuario { get; set; }
        [Display(Name = "Password Usuario")]

        public string password_usuario { get; set; }
        [Display(Name = "Correo Electronico")]

        public string email { get; set; }
    }
}
